### ISSUE TITLE
Provide a live demo

### ISSUE THREAD

**Issue by E-fais** [keerthana-1/ShoppingList#1]
Hi, you can host this html website using github pages, so that viewers can see your project without downloading and running the code. See this documentation :https://pages.github.com/
Thanks

**Comment by keerthana-1** [comment]
> Hi, you can host this html website using github pages, so that viewers can see your project without downloading and running the code. See this documentation :https://pages.github.com/ Thanks

Hi, I have actually deployed it on netlify. I have updated the link in readme. Please check.
